### ISSUE TITLE
Suggestion: Use another sys-path or use ACPI command

### ISSUE THREAD

**Issue by michaelkrisper** [phragment/tp-battery-icon#2]
Currently the path of sysfs is `/sys/devices/platform/smapi`, but i think this path exists only on thinkpads.

A more general approach would be following path:  `/sys/class/power_supply` (see https://wiki.archlinux.org/index.php/ACPI_modules#Updates_since_2.6.24)

OR:

This acpi command could be executed: `acpi -i`

```
import subprocess
subprocess.call(["acpi", "-i"])
```

**Comment by phragment** [comment]
With version 0.2 (aee936e) this is implemented. Thanks for the feedback!
